version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - tpye: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

